[alias]
cov = "llvm-cov --all-features --workspace --html"
tests = "test --all-features --workspace"
lints = "clippy --all-features --all-targets --workspace -- -D warnings"

[env]
RUST_BACKTRACE = "1"
